// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"github.com/SliverHornTrident/shadow/plugin/admin/model"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newMenusApis(db *gorm.DB, opts ...gen.DOOption) menusApis {
	_menusApis := menusApis{}

	_menusApis.menusApisDo.UseDB(db, opts...)
	_menusApis.menusApisDo.UseModel(&model.MenusApis{})

	tableName := _menusApis.menusApisDo.TableName()
	_menusApis.ALL = field.NewAsterisk(tableName)
	_menusApis.ApiId = field.NewUint(tableName, "api_id")
	_menusApis.MenuId = field.NewUint(tableName, "menu_id")
	_menusApis.Api = menusApisBelongsToApi{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Api", "model.Api"),
	}

	_menusApis.Menu = menusApisBelongsToMenu{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Menu", "model.Menu"),
		Buttons: struct {
			field.RelationField
			Menu struct {
				field.RelationField
			}
			Apis struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("Menu.Buttons", "model.MenuButton"),
			Menu: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Menu.Buttons.Menu", "model.Menu"),
			},
			Apis: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Menu.Buttons.Apis", "model.Api"),
			},
		},
		Parameters: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Menu.Parameters", "model.MenuParameter"),
		},
		Apis: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Menu.Apis", "model.Api"),
		},
	}

	_menusApis.fillFieldMap()

	return _menusApis
}

type menusApis struct {
	menusApisDo

	ALL    field.Asterisk
	ApiId  field.Uint
	MenuId field.Uint
	Api    menusApisBelongsToApi

	Menu menusApisBelongsToMenu

	fieldMap map[string]field.Expr
}

func (m menusApis) Table(newTableName string) *menusApis {
	m.menusApisDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m menusApis) As(alias string) *menusApis {
	m.menusApisDo.DO = *(m.menusApisDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *menusApis) updateTableName(table string) *menusApis {
	m.ALL = field.NewAsterisk(table)
	m.ApiId = field.NewUint(table, "api_id")
	m.MenuId = field.NewUint(table, "menu_id")

	m.fillFieldMap()

	return m
}

func (m *menusApis) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *menusApis) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 4)
	m.fieldMap["api_id"] = m.ApiId
	m.fieldMap["menu_id"] = m.MenuId

}

func (m menusApis) clone(db *gorm.DB) menusApis {
	m.menusApisDo.ReplaceConnPool(db.Statement.ConnPool)
	return m
}

func (m menusApis) replaceDB(db *gorm.DB) menusApis {
	m.menusApisDo.ReplaceDB(db)
	return m
}

type menusApisBelongsToApi struct {
	db *gorm.DB

	field.RelationField
}

func (a menusApisBelongsToApi) Where(conds ...field.Expr) *menusApisBelongsToApi {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a menusApisBelongsToApi) WithContext(ctx context.Context) *menusApisBelongsToApi {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a menusApisBelongsToApi) Session(session *gorm.Session) *menusApisBelongsToApi {
	a.db = a.db.Session(session)
	return &a
}

func (a menusApisBelongsToApi) Model(m *model.MenusApis) *menusApisBelongsToApiTx {
	return &menusApisBelongsToApiTx{a.db.Model(m).Association(a.Name())}
}

type menusApisBelongsToApiTx struct{ tx *gorm.Association }

func (a menusApisBelongsToApiTx) Find() (result *model.Api, err error) {
	return result, a.tx.Find(&result)
}

func (a menusApisBelongsToApiTx) Append(values ...*model.Api) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a menusApisBelongsToApiTx) Replace(values ...*model.Api) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a menusApisBelongsToApiTx) Delete(values ...*model.Api) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a menusApisBelongsToApiTx) Clear() error {
	return a.tx.Clear()
}

func (a menusApisBelongsToApiTx) Count() int64 {
	return a.tx.Count()
}

type menusApisBelongsToMenu struct {
	db *gorm.DB

	field.RelationField

	Buttons struct {
		field.RelationField
		Menu struct {
			field.RelationField
		}
		Apis struct {
			field.RelationField
		}
	}
	Parameters struct {
		field.RelationField
	}
	Apis struct {
		field.RelationField
	}
}

func (a menusApisBelongsToMenu) Where(conds ...field.Expr) *menusApisBelongsToMenu {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a menusApisBelongsToMenu) WithContext(ctx context.Context) *menusApisBelongsToMenu {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a menusApisBelongsToMenu) Session(session *gorm.Session) *menusApisBelongsToMenu {
	a.db = a.db.Session(session)
	return &a
}

func (a menusApisBelongsToMenu) Model(m *model.MenusApis) *menusApisBelongsToMenuTx {
	return &menusApisBelongsToMenuTx{a.db.Model(m).Association(a.Name())}
}

type menusApisBelongsToMenuTx struct{ tx *gorm.Association }

func (a menusApisBelongsToMenuTx) Find() (result *model.Menu, err error) {
	return result, a.tx.Find(&result)
}

func (a menusApisBelongsToMenuTx) Append(values ...*model.Menu) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a menusApisBelongsToMenuTx) Replace(values ...*model.Menu) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a menusApisBelongsToMenuTx) Delete(values ...*model.Menu) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a menusApisBelongsToMenuTx) Clear() error {
	return a.tx.Clear()
}

func (a menusApisBelongsToMenuTx) Count() int64 {
	return a.tx.Count()
}

type menusApisDo struct{ gen.DO }

type IMenusApisDo interface {
	gen.SubQuery
	Debug() IMenusApisDo
	WithContext(ctx context.Context) IMenusApisDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IMenusApisDo
	WriteDB() IMenusApisDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IMenusApisDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IMenusApisDo
	Not(conds ...gen.Condition) IMenusApisDo
	Or(conds ...gen.Condition) IMenusApisDo
	Select(conds ...field.Expr) IMenusApisDo
	Where(conds ...gen.Condition) IMenusApisDo
	Order(conds ...field.Expr) IMenusApisDo
	Distinct(cols ...field.Expr) IMenusApisDo
	Omit(cols ...field.Expr) IMenusApisDo
	Join(table schema.Tabler, on ...field.Expr) IMenusApisDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IMenusApisDo
	RightJoin(table schema.Tabler, on ...field.Expr) IMenusApisDo
	Group(cols ...field.Expr) IMenusApisDo
	Having(conds ...gen.Condition) IMenusApisDo
	Limit(limit int) IMenusApisDo
	Offset(offset int) IMenusApisDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IMenusApisDo
	Unscoped() IMenusApisDo
	Create(values ...*model.MenusApis) error
	CreateInBatches(values []*model.MenusApis, batchSize int) error
	Save(values ...*model.MenusApis) error
	First() (*model.MenusApis, error)
	Take() (*model.MenusApis, error)
	Last() (*model.MenusApis, error)
	Find() ([]*model.MenusApis, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.MenusApis, err error)
	FindInBatches(result *[]*model.MenusApis, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.MenusApis) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IMenusApisDo
	Assign(attrs ...field.AssignExpr) IMenusApisDo
	Joins(fields ...field.RelationField) IMenusApisDo
	Preload(fields ...field.RelationField) IMenusApisDo
	FirstOrInit() (*model.MenusApis, error)
	FirstOrCreate() (*model.MenusApis, error)
	FindByPage(offset int, limit int) (result []*model.MenusApis, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IMenusApisDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (m menusApisDo) Debug() IMenusApisDo {
	return m.withDO(m.DO.Debug())
}

func (m menusApisDo) WithContext(ctx context.Context) IMenusApisDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m menusApisDo) ReadDB() IMenusApisDo {
	return m.Clauses(dbresolver.Read)
}

func (m menusApisDo) WriteDB() IMenusApisDo {
	return m.Clauses(dbresolver.Write)
}

func (m menusApisDo) Session(config *gorm.Session) IMenusApisDo {
	return m.withDO(m.DO.Session(config))
}

func (m menusApisDo) Clauses(conds ...clause.Expression) IMenusApisDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m menusApisDo) Returning(value interface{}, columns ...string) IMenusApisDo {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m menusApisDo) Not(conds ...gen.Condition) IMenusApisDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m menusApisDo) Or(conds ...gen.Condition) IMenusApisDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m menusApisDo) Select(conds ...field.Expr) IMenusApisDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m menusApisDo) Where(conds ...gen.Condition) IMenusApisDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m menusApisDo) Order(conds ...field.Expr) IMenusApisDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m menusApisDo) Distinct(cols ...field.Expr) IMenusApisDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m menusApisDo) Omit(cols ...field.Expr) IMenusApisDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m menusApisDo) Join(table schema.Tabler, on ...field.Expr) IMenusApisDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m menusApisDo) LeftJoin(table schema.Tabler, on ...field.Expr) IMenusApisDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m menusApisDo) RightJoin(table schema.Tabler, on ...field.Expr) IMenusApisDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m menusApisDo) Group(cols ...field.Expr) IMenusApisDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m menusApisDo) Having(conds ...gen.Condition) IMenusApisDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m menusApisDo) Limit(limit int) IMenusApisDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m menusApisDo) Offset(offset int) IMenusApisDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m menusApisDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IMenusApisDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m menusApisDo) Unscoped() IMenusApisDo {
	return m.withDO(m.DO.Unscoped())
}

func (m menusApisDo) Create(values ...*model.MenusApis) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m menusApisDo) CreateInBatches(values []*model.MenusApis, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m menusApisDo) Save(values ...*model.MenusApis) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m menusApisDo) First() (*model.MenusApis, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.MenusApis), nil
	}
}

func (m menusApisDo) Take() (*model.MenusApis, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.MenusApis), nil
	}
}

func (m menusApisDo) Last() (*model.MenusApis, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.MenusApis), nil
	}
}

func (m menusApisDo) Find() ([]*model.MenusApis, error) {
	result, err := m.DO.Find()
	return result.([]*model.MenusApis), err
}

func (m menusApisDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.MenusApis, err error) {
	buf := make([]*model.MenusApis, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m menusApisDo) FindInBatches(result *[]*model.MenusApis, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m menusApisDo) Attrs(attrs ...field.AssignExpr) IMenusApisDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m menusApisDo) Assign(attrs ...field.AssignExpr) IMenusApisDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m menusApisDo) Joins(fields ...field.RelationField) IMenusApisDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m menusApisDo) Preload(fields ...field.RelationField) IMenusApisDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m menusApisDo) FirstOrInit() (*model.MenusApis, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.MenusApis), nil
	}
}

func (m menusApisDo) FirstOrCreate() (*model.MenusApis, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.MenusApis), nil
	}
}

func (m menusApisDo) FindByPage(offset int, limit int) (result []*model.MenusApis, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m menusApisDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m menusApisDo) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m menusApisDo) Delete(models ...*model.MenusApis) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *menusApisDo) withDO(do gen.Dao) *menusApisDo {
	m.DO = *do.(*gen.DO)
	return m
}
