// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"github.com/SliverHornTrident/shadow/plugin/admin/model"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newLanguageMessage(db *gorm.DB, opts ...gen.DOOption) languageMessage {
	_languageMessage := languageMessage{}

	_languageMessage.languageMessageDo.UseDB(db, opts...)
	_languageMessage.languageMessageDo.UseModel(&model.LanguageMessage{})

	tableName := _languageMessage.languageMessageDo.TableName()
	_languageMessage.ALL = field.NewAsterisk(tableName)
	_languageMessage.Id = field.NewString(tableName, "id")
	_languageMessage.Tag = field.NewString(tableName, "tag")
	_languageMessage.Hash = field.NewString(tableName, "hash")
	_languageMessage.Description = field.NewString(tableName, "description")
	_languageMessage.LeftDelimiter = field.NewString(tableName, "left_delimiter")
	_languageMessage.RightDelimiter = field.NewString(tableName, "right_delimiter")
	_languageMessage.Zero = field.NewString(tableName, "zero")
	_languageMessage.One = field.NewString(tableName, "one")
	_languageMessage.Two = field.NewString(tableName, "two")
	_languageMessage.Few = field.NewString(tableName, "few")
	_languageMessage.Many = field.NewString(tableName, "many")
	_languageMessage.Other = field.NewString(tableName, "other")

	_languageMessage.fillFieldMap()

	return _languageMessage
}

type languageMessage struct {
	languageMessageDo

	ALL            field.Asterisk
	Id             field.String
	Tag            field.String
	Hash           field.String
	Description    field.String
	LeftDelimiter  field.String
	RightDelimiter field.String
	Zero           field.String
	One            field.String
	Two            field.String
	Few            field.String
	Many           field.String
	Other          field.String

	fieldMap map[string]field.Expr
}

func (l languageMessage) Table(newTableName string) *languageMessage {
	l.languageMessageDo.UseTable(newTableName)
	return l.updateTableName(newTableName)
}

func (l languageMessage) As(alias string) *languageMessage {
	l.languageMessageDo.DO = *(l.languageMessageDo.As(alias).(*gen.DO))
	return l.updateTableName(alias)
}

func (l *languageMessage) updateTableName(table string) *languageMessage {
	l.ALL = field.NewAsterisk(table)
	l.Id = field.NewString(table, "id")
	l.Tag = field.NewString(table, "tag")
	l.Hash = field.NewString(table, "hash")
	l.Description = field.NewString(table, "description")
	l.LeftDelimiter = field.NewString(table, "left_delimiter")
	l.RightDelimiter = field.NewString(table, "right_delimiter")
	l.Zero = field.NewString(table, "zero")
	l.One = field.NewString(table, "one")
	l.Two = field.NewString(table, "two")
	l.Few = field.NewString(table, "few")
	l.Many = field.NewString(table, "many")
	l.Other = field.NewString(table, "other")

	l.fillFieldMap()

	return l
}

func (l *languageMessage) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := l.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (l *languageMessage) fillFieldMap() {
	l.fieldMap = make(map[string]field.Expr, 12)
	l.fieldMap["id"] = l.Id
	l.fieldMap["tag"] = l.Tag
	l.fieldMap["hash"] = l.Hash
	l.fieldMap["description"] = l.Description
	l.fieldMap["left_delimiter"] = l.LeftDelimiter
	l.fieldMap["right_delimiter"] = l.RightDelimiter
	l.fieldMap["zero"] = l.Zero
	l.fieldMap["one"] = l.One
	l.fieldMap["two"] = l.Two
	l.fieldMap["few"] = l.Few
	l.fieldMap["many"] = l.Many
	l.fieldMap["other"] = l.Other
}

func (l languageMessage) clone(db *gorm.DB) languageMessage {
	l.languageMessageDo.ReplaceConnPool(db.Statement.ConnPool)
	return l
}

func (l languageMessage) replaceDB(db *gorm.DB) languageMessage {
	l.languageMessageDo.ReplaceDB(db)
	return l
}

type languageMessageDo struct{ gen.DO }

type ILanguageMessageDo interface {
	gen.SubQuery
	Debug() ILanguageMessageDo
	WithContext(ctx context.Context) ILanguageMessageDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ILanguageMessageDo
	WriteDB() ILanguageMessageDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ILanguageMessageDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ILanguageMessageDo
	Not(conds ...gen.Condition) ILanguageMessageDo
	Or(conds ...gen.Condition) ILanguageMessageDo
	Select(conds ...field.Expr) ILanguageMessageDo
	Where(conds ...gen.Condition) ILanguageMessageDo
	Order(conds ...field.Expr) ILanguageMessageDo
	Distinct(cols ...field.Expr) ILanguageMessageDo
	Omit(cols ...field.Expr) ILanguageMessageDo
	Join(table schema.Tabler, on ...field.Expr) ILanguageMessageDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ILanguageMessageDo
	RightJoin(table schema.Tabler, on ...field.Expr) ILanguageMessageDo
	Group(cols ...field.Expr) ILanguageMessageDo
	Having(conds ...gen.Condition) ILanguageMessageDo
	Limit(limit int) ILanguageMessageDo
	Offset(offset int) ILanguageMessageDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ILanguageMessageDo
	Unscoped() ILanguageMessageDo
	Create(values ...*model.LanguageMessage) error
	CreateInBatches(values []*model.LanguageMessage, batchSize int) error
	Save(values ...*model.LanguageMessage) error
	First() (*model.LanguageMessage, error)
	Take() (*model.LanguageMessage, error)
	Last() (*model.LanguageMessage, error)
	Find() ([]*model.LanguageMessage, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.LanguageMessage, err error)
	FindInBatches(result *[]*model.LanguageMessage, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.LanguageMessage) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ILanguageMessageDo
	Assign(attrs ...field.AssignExpr) ILanguageMessageDo
	Joins(fields ...field.RelationField) ILanguageMessageDo
	Preload(fields ...field.RelationField) ILanguageMessageDo
	FirstOrInit() (*model.LanguageMessage, error)
	FirstOrCreate() (*model.LanguageMessage, error)
	FindByPage(offset int, limit int) (result []*model.LanguageMessage, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ILanguageMessageDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (l languageMessageDo) Debug() ILanguageMessageDo {
	return l.withDO(l.DO.Debug())
}

func (l languageMessageDo) WithContext(ctx context.Context) ILanguageMessageDo {
	return l.withDO(l.DO.WithContext(ctx))
}

func (l languageMessageDo) ReadDB() ILanguageMessageDo {
	return l.Clauses(dbresolver.Read)
}

func (l languageMessageDo) WriteDB() ILanguageMessageDo {
	return l.Clauses(dbresolver.Write)
}

func (l languageMessageDo) Session(config *gorm.Session) ILanguageMessageDo {
	return l.withDO(l.DO.Session(config))
}

func (l languageMessageDo) Clauses(conds ...clause.Expression) ILanguageMessageDo {
	return l.withDO(l.DO.Clauses(conds...))
}

func (l languageMessageDo) Returning(value interface{}, columns ...string) ILanguageMessageDo {
	return l.withDO(l.DO.Returning(value, columns...))
}

func (l languageMessageDo) Not(conds ...gen.Condition) ILanguageMessageDo {
	return l.withDO(l.DO.Not(conds...))
}

func (l languageMessageDo) Or(conds ...gen.Condition) ILanguageMessageDo {
	return l.withDO(l.DO.Or(conds...))
}

func (l languageMessageDo) Select(conds ...field.Expr) ILanguageMessageDo {
	return l.withDO(l.DO.Select(conds...))
}

func (l languageMessageDo) Where(conds ...gen.Condition) ILanguageMessageDo {
	return l.withDO(l.DO.Where(conds...))
}

func (l languageMessageDo) Order(conds ...field.Expr) ILanguageMessageDo {
	return l.withDO(l.DO.Order(conds...))
}

func (l languageMessageDo) Distinct(cols ...field.Expr) ILanguageMessageDo {
	return l.withDO(l.DO.Distinct(cols...))
}

func (l languageMessageDo) Omit(cols ...field.Expr) ILanguageMessageDo {
	return l.withDO(l.DO.Omit(cols...))
}

func (l languageMessageDo) Join(table schema.Tabler, on ...field.Expr) ILanguageMessageDo {
	return l.withDO(l.DO.Join(table, on...))
}

func (l languageMessageDo) LeftJoin(table schema.Tabler, on ...field.Expr) ILanguageMessageDo {
	return l.withDO(l.DO.LeftJoin(table, on...))
}

func (l languageMessageDo) RightJoin(table schema.Tabler, on ...field.Expr) ILanguageMessageDo {
	return l.withDO(l.DO.RightJoin(table, on...))
}

func (l languageMessageDo) Group(cols ...field.Expr) ILanguageMessageDo {
	return l.withDO(l.DO.Group(cols...))
}

func (l languageMessageDo) Having(conds ...gen.Condition) ILanguageMessageDo {
	return l.withDO(l.DO.Having(conds...))
}

func (l languageMessageDo) Limit(limit int) ILanguageMessageDo {
	return l.withDO(l.DO.Limit(limit))
}

func (l languageMessageDo) Offset(offset int) ILanguageMessageDo {
	return l.withDO(l.DO.Offset(offset))
}

func (l languageMessageDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ILanguageMessageDo {
	return l.withDO(l.DO.Scopes(funcs...))
}

func (l languageMessageDo) Unscoped() ILanguageMessageDo {
	return l.withDO(l.DO.Unscoped())
}

func (l languageMessageDo) Create(values ...*model.LanguageMessage) error {
	if len(values) == 0 {
		return nil
	}
	return l.DO.Create(values)
}

func (l languageMessageDo) CreateInBatches(values []*model.LanguageMessage, batchSize int) error {
	return l.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (l languageMessageDo) Save(values ...*model.LanguageMessage) error {
	if len(values) == 0 {
		return nil
	}
	return l.DO.Save(values)
}

func (l languageMessageDo) First() (*model.LanguageMessage, error) {
	if result, err := l.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.LanguageMessage), nil
	}
}

func (l languageMessageDo) Take() (*model.LanguageMessage, error) {
	if result, err := l.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.LanguageMessage), nil
	}
}

func (l languageMessageDo) Last() (*model.LanguageMessage, error) {
	if result, err := l.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.LanguageMessage), nil
	}
}

func (l languageMessageDo) Find() ([]*model.LanguageMessage, error) {
	result, err := l.DO.Find()
	return result.([]*model.LanguageMessage), err
}

func (l languageMessageDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.LanguageMessage, err error) {
	buf := make([]*model.LanguageMessage, 0, batchSize)
	err = l.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (l languageMessageDo) FindInBatches(result *[]*model.LanguageMessage, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return l.DO.FindInBatches(result, batchSize, fc)
}

func (l languageMessageDo) Attrs(attrs ...field.AssignExpr) ILanguageMessageDo {
	return l.withDO(l.DO.Attrs(attrs...))
}

func (l languageMessageDo) Assign(attrs ...field.AssignExpr) ILanguageMessageDo {
	return l.withDO(l.DO.Assign(attrs...))
}

func (l languageMessageDo) Joins(fields ...field.RelationField) ILanguageMessageDo {
	for _, _f := range fields {
		l = *l.withDO(l.DO.Joins(_f))
	}
	return &l
}

func (l languageMessageDo) Preload(fields ...field.RelationField) ILanguageMessageDo {
	for _, _f := range fields {
		l = *l.withDO(l.DO.Preload(_f))
	}
	return &l
}

func (l languageMessageDo) FirstOrInit() (*model.LanguageMessage, error) {
	if result, err := l.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.LanguageMessage), nil
	}
}

func (l languageMessageDo) FirstOrCreate() (*model.LanguageMessage, error) {
	if result, err := l.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.LanguageMessage), nil
	}
}

func (l languageMessageDo) FindByPage(offset int, limit int) (result []*model.LanguageMessage, count int64, err error) {
	result, err = l.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = l.Offset(-1).Limit(-1).Count()
	return
}

func (l languageMessageDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = l.Count()
	if err != nil {
		return
	}

	err = l.Offset(offset).Limit(limit).Scan(result)
	return
}

func (l languageMessageDo) Scan(result interface{}) (err error) {
	return l.DO.Scan(result)
}

func (l languageMessageDo) Delete(models ...*model.LanguageMessage) (result gen.ResultInfo, err error) {
	return l.DO.Delete(models)
}

func (l *languageMessageDo) withDO(do gen.Dao) *languageMessageDo {
	l.DO = *do.(*gen.DO)
	return l
}
