// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"github.com/SliverHornTrident/shadow/plugin/admin/model"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newMenu(db *gorm.DB, opts ...gen.DOOption) menu {
	_menu := menu{}

	_menu.menuDo.UseDB(db, opts...)
	_menu.menuDo.UseModel(&model.Menu{})

	tableName := _menu.menuDo.TableName()
	_menu.ALL = field.NewAsterisk(tableName)
	_menu.ID = field.NewUint(tableName, "id")
	_menu.CreatedAt = field.NewTime(tableName, "created_at")
	_menu.UpdatedAt = field.NewTime(tableName, "updated_at")
	_menu.DeletedAt = field.NewTime(tableName, "deleted_at")
	_menu.IsDelete = field.NewUint(tableName, "is_delete")
	_menu.Name = field.NewString(tableName, "name")
	_menu.Icon = field.NewString(tableName, "icon")
	_menu.Path = field.NewString(tableName, "path")
	_menu.Title = field.NewString(tableName, "title")
	_menu.Component = field.NewString(tableName, "component")
	_menu.Highlight = field.NewString(tableName, "highlight")
	_menu.IsHidden = field.NewBool(tableName, "hidden")
	_menu.AutoClose = field.NewBool(tableName, "auto_close")
	_menu.IsDefault = field.NewBool(tableName, "is_default")
	_menu.KeepAlive = field.NewBool(tableName, "keep_alive")
	_menu.Sort = field.NewInt(tableName, "sort")
	_menu.Level = field.NewUint(tableName, "level")
	_menu.ParentId = field.NewUint(tableName, "parent_id")
	_menu.Buttons = menuHasManyButtons{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Buttons", "model.MenuButton"),
		Menu: struct {
			field.RelationField
			Buttons struct {
				field.RelationField
			}
			Parameters struct {
				field.RelationField
			}
			Apis struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("Buttons.Menu", "model.Menu"),
			Buttons: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Buttons.Menu.Buttons", "model.MenuButton"),
			},
			Parameters: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Buttons.Menu.Parameters", "model.MenuParameter"),
			},
			Apis: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Buttons.Menu.Apis", "model.Api"),
			},
		},
		Apis: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Buttons.Apis", "model.Api"),
		},
	}

	_menu.Parameters = menuHasManyParameters{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Parameters", "model.MenuParameter"),
	}

	_menu.Apis = menuManyToManyApis{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Apis", "model.Api"),
	}

	_menu.fillFieldMap()

	return _menu
}

type menu struct {
	menuDo

	ALL       field.Asterisk
	ID        field.Uint
	CreatedAt field.Time
	UpdatedAt field.Time
	DeletedAt field.Time
	IsDelete  field.Uint
	Name      field.String
	Icon      field.String
	Path      field.String
	Title     field.String
	Component field.String
	Highlight field.String
	IsHidden  field.Bool
	AutoClose field.Bool
	IsDefault field.Bool
	KeepAlive field.Bool
	Sort      field.Int
	Level     field.Uint
	ParentId  field.Uint
	Buttons   menuHasManyButtons

	Parameters menuHasManyParameters

	Apis menuManyToManyApis

	fieldMap map[string]field.Expr
}

func (m menu) Table(newTableName string) *menu {
	m.menuDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m menu) As(alias string) *menu {
	m.menuDo.DO = *(m.menuDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *menu) updateTableName(table string) *menu {
	m.ALL = field.NewAsterisk(table)
	m.ID = field.NewUint(table, "id")
	m.CreatedAt = field.NewTime(table, "created_at")
	m.UpdatedAt = field.NewTime(table, "updated_at")
	m.DeletedAt = field.NewTime(table, "deleted_at")
	m.IsDelete = field.NewUint(table, "is_delete")
	m.Name = field.NewString(table, "name")
	m.Icon = field.NewString(table, "icon")
	m.Path = field.NewString(table, "path")
	m.Title = field.NewString(table, "title")
	m.Component = field.NewString(table, "component")
	m.Highlight = field.NewString(table, "highlight")
	m.IsHidden = field.NewBool(table, "hidden")
	m.AutoClose = field.NewBool(table, "auto_close")
	m.IsDefault = field.NewBool(table, "is_default")
	m.KeepAlive = field.NewBool(table, "keep_alive")
	m.Sort = field.NewInt(table, "sort")
	m.Level = field.NewUint(table, "level")
	m.ParentId = field.NewUint(table, "parent_id")

	m.fillFieldMap()

	return m
}

func (m *menu) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *menu) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 21)
	m.fieldMap["id"] = m.ID
	m.fieldMap["created_at"] = m.CreatedAt
	m.fieldMap["updated_at"] = m.UpdatedAt
	m.fieldMap["deleted_at"] = m.DeletedAt
	m.fieldMap["is_delete"] = m.IsDelete
	m.fieldMap["name"] = m.Name
	m.fieldMap["icon"] = m.Icon
	m.fieldMap["path"] = m.Path
	m.fieldMap["title"] = m.Title
	m.fieldMap["component"] = m.Component
	m.fieldMap["highlight"] = m.Highlight
	m.fieldMap["hidden"] = m.IsHidden
	m.fieldMap["auto_close"] = m.AutoClose
	m.fieldMap["is_default"] = m.IsDefault
	m.fieldMap["keep_alive"] = m.KeepAlive
	m.fieldMap["sort"] = m.Sort
	m.fieldMap["level"] = m.Level
	m.fieldMap["parent_id"] = m.ParentId

}

func (m menu) clone(db *gorm.DB) menu {
	m.menuDo.ReplaceConnPool(db.Statement.ConnPool)
	return m
}

func (m menu) replaceDB(db *gorm.DB) menu {
	m.menuDo.ReplaceDB(db)
	return m
}

type menuHasManyButtons struct {
	db *gorm.DB

	field.RelationField

	Menu struct {
		field.RelationField
		Buttons struct {
			field.RelationField
		}
		Parameters struct {
			field.RelationField
		}
		Apis struct {
			field.RelationField
		}
	}
	Apis struct {
		field.RelationField
	}
}

func (a menuHasManyButtons) Where(conds ...field.Expr) *menuHasManyButtons {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a menuHasManyButtons) WithContext(ctx context.Context) *menuHasManyButtons {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a menuHasManyButtons) Session(session *gorm.Session) *menuHasManyButtons {
	a.db = a.db.Session(session)
	return &a
}

func (a menuHasManyButtons) Model(m *model.Menu) *menuHasManyButtonsTx {
	return &menuHasManyButtonsTx{a.db.Model(m).Association(a.Name())}
}

type menuHasManyButtonsTx struct{ tx *gorm.Association }

func (a menuHasManyButtonsTx) Find() (result []*model.MenuButton, err error) {
	return result, a.tx.Find(&result)
}

func (a menuHasManyButtonsTx) Append(values ...*model.MenuButton) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a menuHasManyButtonsTx) Replace(values ...*model.MenuButton) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a menuHasManyButtonsTx) Delete(values ...*model.MenuButton) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a menuHasManyButtonsTx) Clear() error {
	return a.tx.Clear()
}

func (a menuHasManyButtonsTx) Count() int64 {
	return a.tx.Count()
}

type menuHasManyParameters struct {
	db *gorm.DB

	field.RelationField
}

func (a menuHasManyParameters) Where(conds ...field.Expr) *menuHasManyParameters {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a menuHasManyParameters) WithContext(ctx context.Context) *menuHasManyParameters {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a menuHasManyParameters) Session(session *gorm.Session) *menuHasManyParameters {
	a.db = a.db.Session(session)
	return &a
}

func (a menuHasManyParameters) Model(m *model.Menu) *menuHasManyParametersTx {
	return &menuHasManyParametersTx{a.db.Model(m).Association(a.Name())}
}

type menuHasManyParametersTx struct{ tx *gorm.Association }

func (a menuHasManyParametersTx) Find() (result []*model.MenuParameter, err error) {
	return result, a.tx.Find(&result)
}

func (a menuHasManyParametersTx) Append(values ...*model.MenuParameter) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a menuHasManyParametersTx) Replace(values ...*model.MenuParameter) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a menuHasManyParametersTx) Delete(values ...*model.MenuParameter) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a menuHasManyParametersTx) Clear() error {
	return a.tx.Clear()
}

func (a menuHasManyParametersTx) Count() int64 {
	return a.tx.Count()
}

type menuManyToManyApis struct {
	db *gorm.DB

	field.RelationField
}

func (a menuManyToManyApis) Where(conds ...field.Expr) *menuManyToManyApis {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a menuManyToManyApis) WithContext(ctx context.Context) *menuManyToManyApis {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a menuManyToManyApis) Session(session *gorm.Session) *menuManyToManyApis {
	a.db = a.db.Session(session)
	return &a
}

func (a menuManyToManyApis) Model(m *model.Menu) *menuManyToManyApisTx {
	return &menuManyToManyApisTx{a.db.Model(m).Association(a.Name())}
}

type menuManyToManyApisTx struct{ tx *gorm.Association }

func (a menuManyToManyApisTx) Find() (result []*model.Api, err error) {
	return result, a.tx.Find(&result)
}

func (a menuManyToManyApisTx) Append(values ...*model.Api) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a menuManyToManyApisTx) Replace(values ...*model.Api) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a menuManyToManyApisTx) Delete(values ...*model.Api) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a menuManyToManyApisTx) Clear() error {
	return a.tx.Clear()
}

func (a menuManyToManyApisTx) Count() int64 {
	return a.tx.Count()
}

type menuDo struct{ gen.DO }

type IMenuDo interface {
	gen.SubQuery
	Debug() IMenuDo
	WithContext(ctx context.Context) IMenuDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IMenuDo
	WriteDB() IMenuDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IMenuDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IMenuDo
	Not(conds ...gen.Condition) IMenuDo
	Or(conds ...gen.Condition) IMenuDo
	Select(conds ...field.Expr) IMenuDo
	Where(conds ...gen.Condition) IMenuDo
	Order(conds ...field.Expr) IMenuDo
	Distinct(cols ...field.Expr) IMenuDo
	Omit(cols ...field.Expr) IMenuDo
	Join(table schema.Tabler, on ...field.Expr) IMenuDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IMenuDo
	RightJoin(table schema.Tabler, on ...field.Expr) IMenuDo
	Group(cols ...field.Expr) IMenuDo
	Having(conds ...gen.Condition) IMenuDo
	Limit(limit int) IMenuDo
	Offset(offset int) IMenuDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IMenuDo
	Unscoped() IMenuDo
	Create(values ...*model.Menu) error
	CreateInBatches(values []*model.Menu, batchSize int) error
	Save(values ...*model.Menu) error
	First() (*model.Menu, error)
	Take() (*model.Menu, error)
	Last() (*model.Menu, error)
	Find() ([]*model.Menu, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Menu, err error)
	FindInBatches(result *[]*model.Menu, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Menu) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IMenuDo
	Assign(attrs ...field.AssignExpr) IMenuDo
	Joins(fields ...field.RelationField) IMenuDo
	Preload(fields ...field.RelationField) IMenuDo
	FirstOrInit() (*model.Menu, error)
	FirstOrCreate() (*model.Menu, error)
	FindByPage(offset int, limit int) (result []*model.Menu, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IMenuDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (m menuDo) Debug() IMenuDo {
	return m.withDO(m.DO.Debug())
}

func (m menuDo) WithContext(ctx context.Context) IMenuDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m menuDo) ReadDB() IMenuDo {
	return m.Clauses(dbresolver.Read)
}

func (m menuDo) WriteDB() IMenuDo {
	return m.Clauses(dbresolver.Write)
}

func (m menuDo) Session(config *gorm.Session) IMenuDo {
	return m.withDO(m.DO.Session(config))
}

func (m menuDo) Clauses(conds ...clause.Expression) IMenuDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m menuDo) Returning(value interface{}, columns ...string) IMenuDo {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m menuDo) Not(conds ...gen.Condition) IMenuDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m menuDo) Or(conds ...gen.Condition) IMenuDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m menuDo) Select(conds ...field.Expr) IMenuDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m menuDo) Where(conds ...gen.Condition) IMenuDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m menuDo) Order(conds ...field.Expr) IMenuDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m menuDo) Distinct(cols ...field.Expr) IMenuDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m menuDo) Omit(cols ...field.Expr) IMenuDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m menuDo) Join(table schema.Tabler, on ...field.Expr) IMenuDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m menuDo) LeftJoin(table schema.Tabler, on ...field.Expr) IMenuDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m menuDo) RightJoin(table schema.Tabler, on ...field.Expr) IMenuDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m menuDo) Group(cols ...field.Expr) IMenuDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m menuDo) Having(conds ...gen.Condition) IMenuDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m menuDo) Limit(limit int) IMenuDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m menuDo) Offset(offset int) IMenuDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m menuDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IMenuDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m menuDo) Unscoped() IMenuDo {
	return m.withDO(m.DO.Unscoped())
}

func (m menuDo) Create(values ...*model.Menu) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m menuDo) CreateInBatches(values []*model.Menu, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m menuDo) Save(values ...*model.Menu) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m menuDo) First() (*model.Menu, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Menu), nil
	}
}

func (m menuDo) Take() (*model.Menu, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Menu), nil
	}
}

func (m menuDo) Last() (*model.Menu, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Menu), nil
	}
}

func (m menuDo) Find() ([]*model.Menu, error) {
	result, err := m.DO.Find()
	return result.([]*model.Menu), err
}

func (m menuDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Menu, err error) {
	buf := make([]*model.Menu, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m menuDo) FindInBatches(result *[]*model.Menu, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m menuDo) Attrs(attrs ...field.AssignExpr) IMenuDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m menuDo) Assign(attrs ...field.AssignExpr) IMenuDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m menuDo) Joins(fields ...field.RelationField) IMenuDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m menuDo) Preload(fields ...field.RelationField) IMenuDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m menuDo) FirstOrInit() (*model.Menu, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Menu), nil
	}
}

func (m menuDo) FirstOrCreate() (*model.Menu, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Menu), nil
	}
}

func (m menuDo) FindByPage(offset int, limit int) (result []*model.Menu, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m menuDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m menuDo) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m menuDo) Delete(models ...*model.Menu) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *menuDo) withDO(do gen.Dao) *menuDo {
	m.DO = *do.(*gen.DO)
	return m
}
