// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q                = new(Query)
	Api              *api
	Dictionary       *dictionary
	DictionaryDetail *dictionaryDetail
	Language         *language
	LanguageMessage  *languageMessage
	Menu             *menu
	MenuButton       *menuButton
	MenuButtonsApis  *menuButtonsApis
	MenuParameter    *menuParameter
	MenusApis        *menusApis
	Role             *role
	RolesMenuButtons *rolesMenuButtons
	RolesMenus       *rolesMenus
	User             *user
	UsersRoles       *usersRoles
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	Api = &Q.Api
	Dictionary = &Q.Dictionary
	DictionaryDetail = &Q.DictionaryDetail
	Language = &Q.Language
	LanguageMessage = &Q.LanguageMessage
	Menu = &Q.Menu
	MenuButton = &Q.MenuButton
	MenuButtonsApis = &Q.MenuButtonsApis
	MenuParameter = &Q.MenuParameter
	MenusApis = &Q.MenusApis
	Role = &Q.Role
	RolesMenuButtons = &Q.RolesMenuButtons
	RolesMenus = &Q.RolesMenus
	User = &Q.User
	UsersRoles = &Q.UsersRoles
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:               db,
		Api:              newApi(db, opts...),
		Dictionary:       newDictionary(db, opts...),
		DictionaryDetail: newDictionaryDetail(db, opts...),
		Language:         newLanguage(db, opts...),
		LanguageMessage:  newLanguageMessage(db, opts...),
		Menu:             newMenu(db, opts...),
		MenuButton:       newMenuButton(db, opts...),
		MenuButtonsApis:  newMenuButtonsApis(db, opts...),
		MenuParameter:    newMenuParameter(db, opts...),
		MenusApis:        newMenusApis(db, opts...),
		Role:             newRole(db, opts...),
		RolesMenuButtons: newRolesMenuButtons(db, opts...),
		RolesMenus:       newRolesMenus(db, opts...),
		User:             newUser(db, opts...),
		UsersRoles:       newUsersRoles(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Api              api
	Dictionary       dictionary
	DictionaryDetail dictionaryDetail
	Language         language
	LanguageMessage  languageMessage
	Menu             menu
	MenuButton       menuButton
	MenuButtonsApis  menuButtonsApis
	MenuParameter    menuParameter
	MenusApis        menusApis
	Role             role
	RolesMenuButtons rolesMenuButtons
	RolesMenus       rolesMenus
	User             user
	UsersRoles       usersRoles
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:               db,
		Api:              q.Api.clone(db),
		Dictionary:       q.Dictionary.clone(db),
		DictionaryDetail: q.DictionaryDetail.clone(db),
		Language:         q.Language.clone(db),
		LanguageMessage:  q.LanguageMessage.clone(db),
		Menu:             q.Menu.clone(db),
		MenuButton:       q.MenuButton.clone(db),
		MenuButtonsApis:  q.MenuButtonsApis.clone(db),
		MenuParameter:    q.MenuParameter.clone(db),
		MenusApis:        q.MenusApis.clone(db),
		Role:             q.Role.clone(db),
		RolesMenuButtons: q.RolesMenuButtons.clone(db),
		RolesMenus:       q.RolesMenus.clone(db),
		User:             q.User.clone(db),
		UsersRoles:       q.UsersRoles.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:               db,
		Api:              q.Api.replaceDB(db),
		Dictionary:       q.Dictionary.replaceDB(db),
		DictionaryDetail: q.DictionaryDetail.replaceDB(db),
		Language:         q.Language.replaceDB(db),
		LanguageMessage:  q.LanguageMessage.replaceDB(db),
		Menu:             q.Menu.replaceDB(db),
		MenuButton:       q.MenuButton.replaceDB(db),
		MenuButtonsApis:  q.MenuButtonsApis.replaceDB(db),
		MenuParameter:    q.MenuParameter.replaceDB(db),
		MenusApis:        q.MenusApis.replaceDB(db),
		Role:             q.Role.replaceDB(db),
		RolesMenuButtons: q.RolesMenuButtons.replaceDB(db),
		RolesMenus:       q.RolesMenus.replaceDB(db),
		User:             q.User.replaceDB(db),
		UsersRoles:       q.UsersRoles.replaceDB(db),
	}
}

type queryCtx struct {
	Api              IApiDo
	Dictionary       IDictionaryDo
	DictionaryDetail IDictionaryDetailDo
	Language         ILanguageDo
	LanguageMessage  ILanguageMessageDo
	Menu             IMenuDo
	MenuButton       IMenuButtonDo
	MenuButtonsApis  IMenuButtonsApisDo
	MenuParameter    IMenuParameterDo
	MenusApis        IMenusApisDo
	Role             IRoleDo
	RolesMenuButtons IRolesMenuButtonsDo
	RolesMenus       IRolesMenusDo
	User             IUserDo
	UsersRoles       IUsersRolesDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Api:              q.Api.WithContext(ctx),
		Dictionary:       q.Dictionary.WithContext(ctx),
		DictionaryDetail: q.DictionaryDetail.WithContext(ctx),
		Language:         q.Language.WithContext(ctx),
		LanguageMessage:  q.LanguageMessage.WithContext(ctx),
		Menu:             q.Menu.WithContext(ctx),
		MenuButton:       q.MenuButton.WithContext(ctx),
		MenuButtonsApis:  q.MenuButtonsApis.WithContext(ctx),
		MenuParameter:    q.MenuParameter.WithContext(ctx),
		MenusApis:        q.MenusApis.WithContext(ctx),
		Role:             q.Role.WithContext(ctx),
		RolesMenuButtons: q.RolesMenuButtons.WithContext(ctx),
		RolesMenus:       q.RolesMenus.WithContext(ctx),
		User:             q.User.WithContext(ctx),
		UsersRoles:       q.UsersRoles.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
