// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"github.com/SliverHornTrident/shadow/plugin/admin/model"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newMenuButtonsApis(db *gorm.DB, opts ...gen.DOOption) menuButtonsApis {
	_menuButtonsApis := menuButtonsApis{}

	_menuButtonsApis.menuButtonsApisDo.UseDB(db, opts...)
	_menuButtonsApis.menuButtonsApisDo.UseModel(&model.MenuButtonsApis{})

	tableName := _menuButtonsApis.menuButtonsApisDo.TableName()
	_menuButtonsApis.ALL = field.NewAsterisk(tableName)
	_menuButtonsApis.ApiId = field.NewUint(tableName, "api_id")
	_menuButtonsApis.MenuId = field.NewUint(tableName, "menu_id")
	_menuButtonsApis.MenuButtonId = field.NewUint(tableName, "menu_button_id")
	_menuButtonsApis.Api = menuButtonsApisBelongsToApi{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Api", "model.Api"),
	}

	_menuButtonsApis.Menu = menuButtonsApisBelongsToMenu{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Menu", "model.Menu"),
		Buttons: struct {
			field.RelationField
			Menu struct {
				field.RelationField
			}
			Apis struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("Menu.Buttons", "model.MenuButton"),
			Menu: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Menu.Buttons.Menu", "model.Menu"),
			},
			Apis: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Menu.Buttons.Apis", "model.Api"),
			},
		},
		Parameters: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Menu.Parameters", "model.MenuParameter"),
		},
		Apis: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Menu.Apis", "model.Api"),
		},
	}

	_menuButtonsApis.MenuButton = menuButtonsApisBelongsToMenuButton{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("MenuButton", "model.MenuButton"),
	}

	_menuButtonsApis.fillFieldMap()

	return _menuButtonsApis
}

type menuButtonsApis struct {
	menuButtonsApisDo

	ALL          field.Asterisk
	ApiId        field.Uint
	MenuId       field.Uint
	MenuButtonId field.Uint
	Api          menuButtonsApisBelongsToApi

	Menu menuButtonsApisBelongsToMenu

	MenuButton menuButtonsApisBelongsToMenuButton

	fieldMap map[string]field.Expr
}

func (m menuButtonsApis) Table(newTableName string) *menuButtonsApis {
	m.menuButtonsApisDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m menuButtonsApis) As(alias string) *menuButtonsApis {
	m.menuButtonsApisDo.DO = *(m.menuButtonsApisDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *menuButtonsApis) updateTableName(table string) *menuButtonsApis {
	m.ALL = field.NewAsterisk(table)
	m.ApiId = field.NewUint(table, "api_id")
	m.MenuId = field.NewUint(table, "menu_id")
	m.MenuButtonId = field.NewUint(table, "menu_button_id")

	m.fillFieldMap()

	return m
}

func (m *menuButtonsApis) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *menuButtonsApis) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 6)
	m.fieldMap["api_id"] = m.ApiId
	m.fieldMap["menu_id"] = m.MenuId
	m.fieldMap["menu_button_id"] = m.MenuButtonId

}

func (m menuButtonsApis) clone(db *gorm.DB) menuButtonsApis {
	m.menuButtonsApisDo.ReplaceConnPool(db.Statement.ConnPool)
	return m
}

func (m menuButtonsApis) replaceDB(db *gorm.DB) menuButtonsApis {
	m.menuButtonsApisDo.ReplaceDB(db)
	return m
}

type menuButtonsApisBelongsToApi struct {
	db *gorm.DB

	field.RelationField
}

func (a menuButtonsApisBelongsToApi) Where(conds ...field.Expr) *menuButtonsApisBelongsToApi {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a menuButtonsApisBelongsToApi) WithContext(ctx context.Context) *menuButtonsApisBelongsToApi {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a menuButtonsApisBelongsToApi) Session(session *gorm.Session) *menuButtonsApisBelongsToApi {
	a.db = a.db.Session(session)
	return &a
}

func (a menuButtonsApisBelongsToApi) Model(m *model.MenuButtonsApis) *menuButtonsApisBelongsToApiTx {
	return &menuButtonsApisBelongsToApiTx{a.db.Model(m).Association(a.Name())}
}

type menuButtonsApisBelongsToApiTx struct{ tx *gorm.Association }

func (a menuButtonsApisBelongsToApiTx) Find() (result *model.Api, err error) {
	return result, a.tx.Find(&result)
}

func (a menuButtonsApisBelongsToApiTx) Append(values ...*model.Api) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a menuButtonsApisBelongsToApiTx) Replace(values ...*model.Api) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a menuButtonsApisBelongsToApiTx) Delete(values ...*model.Api) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a menuButtonsApisBelongsToApiTx) Clear() error {
	return a.tx.Clear()
}

func (a menuButtonsApisBelongsToApiTx) Count() int64 {
	return a.tx.Count()
}

type menuButtonsApisBelongsToMenu struct {
	db *gorm.DB

	field.RelationField

	Buttons struct {
		field.RelationField
		Menu struct {
			field.RelationField
		}
		Apis struct {
			field.RelationField
		}
	}
	Parameters struct {
		field.RelationField
	}
	Apis struct {
		field.RelationField
	}
}

func (a menuButtonsApisBelongsToMenu) Where(conds ...field.Expr) *menuButtonsApisBelongsToMenu {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a menuButtonsApisBelongsToMenu) WithContext(ctx context.Context) *menuButtonsApisBelongsToMenu {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a menuButtonsApisBelongsToMenu) Session(session *gorm.Session) *menuButtonsApisBelongsToMenu {
	a.db = a.db.Session(session)
	return &a
}

func (a menuButtonsApisBelongsToMenu) Model(m *model.MenuButtonsApis) *menuButtonsApisBelongsToMenuTx {
	return &menuButtonsApisBelongsToMenuTx{a.db.Model(m).Association(a.Name())}
}

type menuButtonsApisBelongsToMenuTx struct{ tx *gorm.Association }

func (a menuButtonsApisBelongsToMenuTx) Find() (result *model.Menu, err error) {
	return result, a.tx.Find(&result)
}

func (a menuButtonsApisBelongsToMenuTx) Append(values ...*model.Menu) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a menuButtonsApisBelongsToMenuTx) Replace(values ...*model.Menu) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a menuButtonsApisBelongsToMenuTx) Delete(values ...*model.Menu) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a menuButtonsApisBelongsToMenuTx) Clear() error {
	return a.tx.Clear()
}

func (a menuButtonsApisBelongsToMenuTx) Count() int64 {
	return a.tx.Count()
}

type menuButtonsApisBelongsToMenuButton struct {
	db *gorm.DB

	field.RelationField
}

func (a menuButtonsApisBelongsToMenuButton) Where(conds ...field.Expr) *menuButtonsApisBelongsToMenuButton {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a menuButtonsApisBelongsToMenuButton) WithContext(ctx context.Context) *menuButtonsApisBelongsToMenuButton {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a menuButtonsApisBelongsToMenuButton) Session(session *gorm.Session) *menuButtonsApisBelongsToMenuButton {
	a.db = a.db.Session(session)
	return &a
}

func (a menuButtonsApisBelongsToMenuButton) Model(m *model.MenuButtonsApis) *menuButtonsApisBelongsToMenuButtonTx {
	return &menuButtonsApisBelongsToMenuButtonTx{a.db.Model(m).Association(a.Name())}
}

type menuButtonsApisBelongsToMenuButtonTx struct{ tx *gorm.Association }

func (a menuButtonsApisBelongsToMenuButtonTx) Find() (result *model.MenuButton, err error) {
	return result, a.tx.Find(&result)
}

func (a menuButtonsApisBelongsToMenuButtonTx) Append(values ...*model.MenuButton) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a menuButtonsApisBelongsToMenuButtonTx) Replace(values ...*model.MenuButton) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a menuButtonsApisBelongsToMenuButtonTx) Delete(values ...*model.MenuButton) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a menuButtonsApisBelongsToMenuButtonTx) Clear() error {
	return a.tx.Clear()
}

func (a menuButtonsApisBelongsToMenuButtonTx) Count() int64 {
	return a.tx.Count()
}

type menuButtonsApisDo struct{ gen.DO }

type IMenuButtonsApisDo interface {
	gen.SubQuery
	Debug() IMenuButtonsApisDo
	WithContext(ctx context.Context) IMenuButtonsApisDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IMenuButtonsApisDo
	WriteDB() IMenuButtonsApisDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IMenuButtonsApisDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IMenuButtonsApisDo
	Not(conds ...gen.Condition) IMenuButtonsApisDo
	Or(conds ...gen.Condition) IMenuButtonsApisDo
	Select(conds ...field.Expr) IMenuButtonsApisDo
	Where(conds ...gen.Condition) IMenuButtonsApisDo
	Order(conds ...field.Expr) IMenuButtonsApisDo
	Distinct(cols ...field.Expr) IMenuButtonsApisDo
	Omit(cols ...field.Expr) IMenuButtonsApisDo
	Join(table schema.Tabler, on ...field.Expr) IMenuButtonsApisDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IMenuButtonsApisDo
	RightJoin(table schema.Tabler, on ...field.Expr) IMenuButtonsApisDo
	Group(cols ...field.Expr) IMenuButtonsApisDo
	Having(conds ...gen.Condition) IMenuButtonsApisDo
	Limit(limit int) IMenuButtonsApisDo
	Offset(offset int) IMenuButtonsApisDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IMenuButtonsApisDo
	Unscoped() IMenuButtonsApisDo
	Create(values ...*model.MenuButtonsApis) error
	CreateInBatches(values []*model.MenuButtonsApis, batchSize int) error
	Save(values ...*model.MenuButtonsApis) error
	First() (*model.MenuButtonsApis, error)
	Take() (*model.MenuButtonsApis, error)
	Last() (*model.MenuButtonsApis, error)
	Find() ([]*model.MenuButtonsApis, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.MenuButtonsApis, err error)
	FindInBatches(result *[]*model.MenuButtonsApis, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.MenuButtonsApis) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IMenuButtonsApisDo
	Assign(attrs ...field.AssignExpr) IMenuButtonsApisDo
	Joins(fields ...field.RelationField) IMenuButtonsApisDo
	Preload(fields ...field.RelationField) IMenuButtonsApisDo
	FirstOrInit() (*model.MenuButtonsApis, error)
	FirstOrCreate() (*model.MenuButtonsApis, error)
	FindByPage(offset int, limit int) (result []*model.MenuButtonsApis, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IMenuButtonsApisDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (m menuButtonsApisDo) Debug() IMenuButtonsApisDo {
	return m.withDO(m.DO.Debug())
}

func (m menuButtonsApisDo) WithContext(ctx context.Context) IMenuButtonsApisDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m menuButtonsApisDo) ReadDB() IMenuButtonsApisDo {
	return m.Clauses(dbresolver.Read)
}

func (m menuButtonsApisDo) WriteDB() IMenuButtonsApisDo {
	return m.Clauses(dbresolver.Write)
}

func (m menuButtonsApisDo) Session(config *gorm.Session) IMenuButtonsApisDo {
	return m.withDO(m.DO.Session(config))
}

func (m menuButtonsApisDo) Clauses(conds ...clause.Expression) IMenuButtonsApisDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m menuButtonsApisDo) Returning(value interface{}, columns ...string) IMenuButtonsApisDo {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m menuButtonsApisDo) Not(conds ...gen.Condition) IMenuButtonsApisDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m menuButtonsApisDo) Or(conds ...gen.Condition) IMenuButtonsApisDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m menuButtonsApisDo) Select(conds ...field.Expr) IMenuButtonsApisDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m menuButtonsApisDo) Where(conds ...gen.Condition) IMenuButtonsApisDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m menuButtonsApisDo) Order(conds ...field.Expr) IMenuButtonsApisDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m menuButtonsApisDo) Distinct(cols ...field.Expr) IMenuButtonsApisDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m menuButtonsApisDo) Omit(cols ...field.Expr) IMenuButtonsApisDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m menuButtonsApisDo) Join(table schema.Tabler, on ...field.Expr) IMenuButtonsApisDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m menuButtonsApisDo) LeftJoin(table schema.Tabler, on ...field.Expr) IMenuButtonsApisDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m menuButtonsApisDo) RightJoin(table schema.Tabler, on ...field.Expr) IMenuButtonsApisDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m menuButtonsApisDo) Group(cols ...field.Expr) IMenuButtonsApisDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m menuButtonsApisDo) Having(conds ...gen.Condition) IMenuButtonsApisDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m menuButtonsApisDo) Limit(limit int) IMenuButtonsApisDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m menuButtonsApisDo) Offset(offset int) IMenuButtonsApisDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m menuButtonsApisDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IMenuButtonsApisDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m menuButtonsApisDo) Unscoped() IMenuButtonsApisDo {
	return m.withDO(m.DO.Unscoped())
}

func (m menuButtonsApisDo) Create(values ...*model.MenuButtonsApis) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m menuButtonsApisDo) CreateInBatches(values []*model.MenuButtonsApis, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m menuButtonsApisDo) Save(values ...*model.MenuButtonsApis) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m menuButtonsApisDo) First() (*model.MenuButtonsApis, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.MenuButtonsApis), nil
	}
}

func (m menuButtonsApisDo) Take() (*model.MenuButtonsApis, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.MenuButtonsApis), nil
	}
}

func (m menuButtonsApisDo) Last() (*model.MenuButtonsApis, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.MenuButtonsApis), nil
	}
}

func (m menuButtonsApisDo) Find() ([]*model.MenuButtonsApis, error) {
	result, err := m.DO.Find()
	return result.([]*model.MenuButtonsApis), err
}

func (m menuButtonsApisDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.MenuButtonsApis, err error) {
	buf := make([]*model.MenuButtonsApis, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m menuButtonsApisDo) FindInBatches(result *[]*model.MenuButtonsApis, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m menuButtonsApisDo) Attrs(attrs ...field.AssignExpr) IMenuButtonsApisDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m menuButtonsApisDo) Assign(attrs ...field.AssignExpr) IMenuButtonsApisDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m menuButtonsApisDo) Joins(fields ...field.RelationField) IMenuButtonsApisDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m menuButtonsApisDo) Preload(fields ...field.RelationField) IMenuButtonsApisDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m menuButtonsApisDo) FirstOrInit() (*model.MenuButtonsApis, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.MenuButtonsApis), nil
	}
}

func (m menuButtonsApisDo) FirstOrCreate() (*model.MenuButtonsApis, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.MenuButtonsApis), nil
	}
}

func (m menuButtonsApisDo) FindByPage(offset int, limit int) (result []*model.MenuButtonsApis, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m menuButtonsApisDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m menuButtonsApisDo) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m menuButtonsApisDo) Delete(models ...*model.MenuButtonsApis) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *menuButtonsApisDo) withDO(do gen.Dao) *menuButtonsApisDo {
	m.DO = *do.(*gen.DO)
	return m
}
