// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"github.com/SliverHornTrident/shadow/plugin/admin/model"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newMenuButton(db *gorm.DB, opts ...gen.DOOption) menuButton {
	_menuButton := menuButton{}

	_menuButton.menuButtonDo.UseDB(db, opts...)
	_menuButton.menuButtonDo.UseModel(&model.MenuButton{})

	tableName := _menuButton.menuButtonDo.TableName()
	_menuButton.ALL = field.NewAsterisk(tableName)
	_menuButton.ID = field.NewUint(tableName, "id")
	_menuButton.CreatedAt = field.NewTime(tableName, "created_at")
	_menuButton.UpdatedAt = field.NewTime(tableName, "updated_at")
	_menuButton.DeletedAt = field.NewTime(tableName, "deleted_at")
	_menuButton.IsDelete = field.NewUint(tableName, "is_delete")
	_menuButton.Icon = field.NewString(tableName, "icon")
	_menuButton.Name = field.NewString(tableName, "name")
	_menuButton.MenuId = field.NewUint(tableName, "menu_id")
	_menuButton.Menu = menuButtonBelongsToMenu{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Menu", "model.Menu"),
		Buttons: struct {
			field.RelationField
			Menu struct {
				field.RelationField
			}
			Apis struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("Menu.Buttons", "model.MenuButton"),
			Menu: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Menu.Buttons.Menu", "model.Menu"),
			},
			Apis: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Menu.Buttons.Apis", "model.Api"),
			},
		},
		Parameters: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Menu.Parameters", "model.MenuParameter"),
		},
		Apis: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Menu.Apis", "model.Api"),
		},
	}

	_menuButton.Apis = menuButtonManyToManyApis{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Apis", "model.Api"),
	}

	_menuButton.fillFieldMap()

	return _menuButton
}

type menuButton struct {
	menuButtonDo

	ALL       field.Asterisk
	ID        field.Uint
	CreatedAt field.Time
	UpdatedAt field.Time
	DeletedAt field.Time
	IsDelete  field.Uint
	Icon      field.String
	Name      field.String
	MenuId    field.Uint
	Menu      menuButtonBelongsToMenu

	Apis menuButtonManyToManyApis

	fieldMap map[string]field.Expr
}

func (m menuButton) Table(newTableName string) *menuButton {
	m.menuButtonDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m menuButton) As(alias string) *menuButton {
	m.menuButtonDo.DO = *(m.menuButtonDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *menuButton) updateTableName(table string) *menuButton {
	m.ALL = field.NewAsterisk(table)
	m.ID = field.NewUint(table, "id")
	m.CreatedAt = field.NewTime(table, "created_at")
	m.UpdatedAt = field.NewTime(table, "updated_at")
	m.DeletedAt = field.NewTime(table, "deleted_at")
	m.IsDelete = field.NewUint(table, "is_delete")
	m.Icon = field.NewString(table, "icon")
	m.Name = field.NewString(table, "name")
	m.MenuId = field.NewUint(table, "menu_id")

	m.fillFieldMap()

	return m
}

func (m *menuButton) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *menuButton) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 10)
	m.fieldMap["id"] = m.ID
	m.fieldMap["created_at"] = m.CreatedAt
	m.fieldMap["updated_at"] = m.UpdatedAt
	m.fieldMap["deleted_at"] = m.DeletedAt
	m.fieldMap["is_delete"] = m.IsDelete
	m.fieldMap["icon"] = m.Icon
	m.fieldMap["name"] = m.Name
	m.fieldMap["menu_id"] = m.MenuId

}

func (m menuButton) clone(db *gorm.DB) menuButton {
	m.menuButtonDo.ReplaceConnPool(db.Statement.ConnPool)
	return m
}

func (m menuButton) replaceDB(db *gorm.DB) menuButton {
	m.menuButtonDo.ReplaceDB(db)
	return m
}

type menuButtonBelongsToMenu struct {
	db *gorm.DB

	field.RelationField

	Buttons struct {
		field.RelationField
		Menu struct {
			field.RelationField
		}
		Apis struct {
			field.RelationField
		}
	}
	Parameters struct {
		field.RelationField
	}
	Apis struct {
		field.RelationField
	}
}

func (a menuButtonBelongsToMenu) Where(conds ...field.Expr) *menuButtonBelongsToMenu {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a menuButtonBelongsToMenu) WithContext(ctx context.Context) *menuButtonBelongsToMenu {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a menuButtonBelongsToMenu) Session(session *gorm.Session) *menuButtonBelongsToMenu {
	a.db = a.db.Session(session)
	return &a
}

func (a menuButtonBelongsToMenu) Model(m *model.MenuButton) *menuButtonBelongsToMenuTx {
	return &menuButtonBelongsToMenuTx{a.db.Model(m).Association(a.Name())}
}

type menuButtonBelongsToMenuTx struct{ tx *gorm.Association }

func (a menuButtonBelongsToMenuTx) Find() (result *model.Menu, err error) {
	return result, a.tx.Find(&result)
}

func (a menuButtonBelongsToMenuTx) Append(values ...*model.Menu) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a menuButtonBelongsToMenuTx) Replace(values ...*model.Menu) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a menuButtonBelongsToMenuTx) Delete(values ...*model.Menu) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a menuButtonBelongsToMenuTx) Clear() error {
	return a.tx.Clear()
}

func (a menuButtonBelongsToMenuTx) Count() int64 {
	return a.tx.Count()
}

type menuButtonManyToManyApis struct {
	db *gorm.DB

	field.RelationField
}

func (a menuButtonManyToManyApis) Where(conds ...field.Expr) *menuButtonManyToManyApis {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a menuButtonManyToManyApis) WithContext(ctx context.Context) *menuButtonManyToManyApis {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a menuButtonManyToManyApis) Session(session *gorm.Session) *menuButtonManyToManyApis {
	a.db = a.db.Session(session)
	return &a
}

func (a menuButtonManyToManyApis) Model(m *model.MenuButton) *menuButtonManyToManyApisTx {
	return &menuButtonManyToManyApisTx{a.db.Model(m).Association(a.Name())}
}

type menuButtonManyToManyApisTx struct{ tx *gorm.Association }

func (a menuButtonManyToManyApisTx) Find() (result []*model.Api, err error) {
	return result, a.tx.Find(&result)
}

func (a menuButtonManyToManyApisTx) Append(values ...*model.Api) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a menuButtonManyToManyApisTx) Replace(values ...*model.Api) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a menuButtonManyToManyApisTx) Delete(values ...*model.Api) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a menuButtonManyToManyApisTx) Clear() error {
	return a.tx.Clear()
}

func (a menuButtonManyToManyApisTx) Count() int64 {
	return a.tx.Count()
}

type menuButtonDo struct{ gen.DO }

type IMenuButtonDo interface {
	gen.SubQuery
	Debug() IMenuButtonDo
	WithContext(ctx context.Context) IMenuButtonDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IMenuButtonDo
	WriteDB() IMenuButtonDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IMenuButtonDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IMenuButtonDo
	Not(conds ...gen.Condition) IMenuButtonDo
	Or(conds ...gen.Condition) IMenuButtonDo
	Select(conds ...field.Expr) IMenuButtonDo
	Where(conds ...gen.Condition) IMenuButtonDo
	Order(conds ...field.Expr) IMenuButtonDo
	Distinct(cols ...field.Expr) IMenuButtonDo
	Omit(cols ...field.Expr) IMenuButtonDo
	Join(table schema.Tabler, on ...field.Expr) IMenuButtonDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IMenuButtonDo
	RightJoin(table schema.Tabler, on ...field.Expr) IMenuButtonDo
	Group(cols ...field.Expr) IMenuButtonDo
	Having(conds ...gen.Condition) IMenuButtonDo
	Limit(limit int) IMenuButtonDo
	Offset(offset int) IMenuButtonDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IMenuButtonDo
	Unscoped() IMenuButtonDo
	Create(values ...*model.MenuButton) error
	CreateInBatches(values []*model.MenuButton, batchSize int) error
	Save(values ...*model.MenuButton) error
	First() (*model.MenuButton, error)
	Take() (*model.MenuButton, error)
	Last() (*model.MenuButton, error)
	Find() ([]*model.MenuButton, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.MenuButton, err error)
	FindInBatches(result *[]*model.MenuButton, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.MenuButton) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IMenuButtonDo
	Assign(attrs ...field.AssignExpr) IMenuButtonDo
	Joins(fields ...field.RelationField) IMenuButtonDo
	Preload(fields ...field.RelationField) IMenuButtonDo
	FirstOrInit() (*model.MenuButton, error)
	FirstOrCreate() (*model.MenuButton, error)
	FindByPage(offset int, limit int) (result []*model.MenuButton, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IMenuButtonDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (m menuButtonDo) Debug() IMenuButtonDo {
	return m.withDO(m.DO.Debug())
}

func (m menuButtonDo) WithContext(ctx context.Context) IMenuButtonDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m menuButtonDo) ReadDB() IMenuButtonDo {
	return m.Clauses(dbresolver.Read)
}

func (m menuButtonDo) WriteDB() IMenuButtonDo {
	return m.Clauses(dbresolver.Write)
}

func (m menuButtonDo) Session(config *gorm.Session) IMenuButtonDo {
	return m.withDO(m.DO.Session(config))
}

func (m menuButtonDo) Clauses(conds ...clause.Expression) IMenuButtonDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m menuButtonDo) Returning(value interface{}, columns ...string) IMenuButtonDo {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m menuButtonDo) Not(conds ...gen.Condition) IMenuButtonDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m menuButtonDo) Or(conds ...gen.Condition) IMenuButtonDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m menuButtonDo) Select(conds ...field.Expr) IMenuButtonDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m menuButtonDo) Where(conds ...gen.Condition) IMenuButtonDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m menuButtonDo) Order(conds ...field.Expr) IMenuButtonDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m menuButtonDo) Distinct(cols ...field.Expr) IMenuButtonDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m menuButtonDo) Omit(cols ...field.Expr) IMenuButtonDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m menuButtonDo) Join(table schema.Tabler, on ...field.Expr) IMenuButtonDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m menuButtonDo) LeftJoin(table schema.Tabler, on ...field.Expr) IMenuButtonDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m menuButtonDo) RightJoin(table schema.Tabler, on ...field.Expr) IMenuButtonDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m menuButtonDo) Group(cols ...field.Expr) IMenuButtonDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m menuButtonDo) Having(conds ...gen.Condition) IMenuButtonDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m menuButtonDo) Limit(limit int) IMenuButtonDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m menuButtonDo) Offset(offset int) IMenuButtonDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m menuButtonDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IMenuButtonDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m menuButtonDo) Unscoped() IMenuButtonDo {
	return m.withDO(m.DO.Unscoped())
}

func (m menuButtonDo) Create(values ...*model.MenuButton) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m menuButtonDo) CreateInBatches(values []*model.MenuButton, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m menuButtonDo) Save(values ...*model.MenuButton) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m menuButtonDo) First() (*model.MenuButton, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.MenuButton), nil
	}
}

func (m menuButtonDo) Take() (*model.MenuButton, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.MenuButton), nil
	}
}

func (m menuButtonDo) Last() (*model.MenuButton, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.MenuButton), nil
	}
}

func (m menuButtonDo) Find() ([]*model.MenuButton, error) {
	result, err := m.DO.Find()
	return result.([]*model.MenuButton), err
}

func (m menuButtonDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.MenuButton, err error) {
	buf := make([]*model.MenuButton, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m menuButtonDo) FindInBatches(result *[]*model.MenuButton, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m menuButtonDo) Attrs(attrs ...field.AssignExpr) IMenuButtonDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m menuButtonDo) Assign(attrs ...field.AssignExpr) IMenuButtonDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m menuButtonDo) Joins(fields ...field.RelationField) IMenuButtonDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m menuButtonDo) Preload(fields ...field.RelationField) IMenuButtonDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m menuButtonDo) FirstOrInit() (*model.MenuButton, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.MenuButton), nil
	}
}

func (m menuButtonDo) FirstOrCreate() (*model.MenuButton, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.MenuButton), nil
	}
}

func (m menuButtonDo) FindByPage(offset int, limit int) (result []*model.MenuButton, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m menuButtonDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m menuButtonDo) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m menuButtonDo) Delete(models ...*model.MenuButton) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *menuButtonDo) withDO(do gen.Dao) *menuButtonDo {
	m.DO = *do.(*gen.DO)
	return m
}
